services:

  registry:
    image: registry:2
    container_name: registry
    hostname: registry
    environment:
      TZ: "Europe/Moscow"
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/live/registry.gusevandrey.ru/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/live/registry.gusevandrey.ru/privkey.pem
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - /home/andrey/docker_repo:/var/lib/registry
      - /etc/letsencrypt:/certs
      - /home/andrey/docker_auth:/auth
