all:
    children:
        site:
            hosts:
                server:
                    ansible_connection: ssh
                    ansible_user: root
                    ansible_host: 89.223.123.40
                    ansible_port: 22

        registry:
            hosts:
                server:
                    ansible_connection: ssh
                    ansible_user: root
                    ansible_host: 89.223.123.40
                    ansible_port: 22